[build]
  base = "frontend"
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_USE_MOCK_API = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200